### ISSUE TITLE
is using string-hash for hashtags safe?

### ISSUE THREAD

**Issue by montyanderson** [Altoros/redis-labs-use-cases#2]
I was looking through the twitter-stream example and I see you make a numeric hash of the hashtag using string-hash- I wondered if this is safe? Surely if there is 2^32 different combinations people will find collisions... no?

**Comment by josx** [comment]
Yes you are right collision is 2^32 and it is safe.
You can get more info on http://www.cse.yorku.ca/~oz/hash.html

**Comment by montyanderson** [comment]
Which of those algorithms does it use?

**Comment by josx** [comment]
Here mofule github https://github.com/darkskyapp/string-hash
_The particular algorithm is quite similar to djb2, by Dan Bernstein and available here. Differences include iterating over the string backwards (as that is faster in JavaScript) and using the XOR operator instead of the addition operator (as described at that page and because it obviates the need for modular arithmetic in JavaScript)._
